/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   urr_sap.h
 *
 * Project:
 * --------
 *   MONZA
 *
 * Description:
 * ------------
 *
 *
 * Author:
 * -------
 * -------
 *
 *===========================================================================
 * $Log:$
 *
 * 11 25 2016 rajesh.sastry
 * [MOLY00214878] Remote SIM 2G/3G part
 *
 * 04 26 2016 vend_mtb_aricent_03
 * [MOLY00174874] [Jade-M][SRLTE+W][MP3][FT][CD][ZTE][Random]CAT�E?�A�X?Current Executing Process:  md1:(MCU_PCORE) [ASSERT] file:pcore/modem/uas/ul2/umac/src/mac_phy.c line:1262
 * SCLE ABort Ind.
 *
 * 04 13 2016 vend_mtb_aricent_03
 * [MOLY00172045] Multiple-PS/Remote-SIM interfaces
 * enum mismatch.
 *
 * 04 11 2016 vend_mtb_aricent_03
 * [MOLY00172045] Multiple-PS/Remote-SIM interfaces
 * Multiple PS UAS Interface Changes for MP3.
 *
 * 04 01 2016 suryakant.tiwari
 * [MOLY00169318] [Feature Request] CS Support during 3G call connection
 * IRNMN_ALPS02612772_MP3_main
 *
 * 03 09 2016 vijay.katakam
 * [MOLY00167983] [MT6755][Jade L6][MP2][CSFB DSDS][HSR][FDD][HSR][4G_Moving][Case Fail][LAT2]PLMN List time is lose to reference phone
 * .
 *
 * 03 09 2016 james-chi-ju.chang
 * [MOLY00167983] [MT6755][Jade L6][MP2][CSFB DSDS][HSR][FDD][HSR][4G_Moving][Case Fail][LAT2]PLMN List time is lose to reference phone
 * .
 *
 * 12 17 2015 wonder.lee
 * [MOLY00144447] Operator Feature/Requirement-VZW DYNAMIC BAND. 
 * 	
 * 	.
 *
 * 12 11 2015 james-chi-ju.chang
 * [MOLY00152730] [LAT2][2015][MT6755 TMO-US][Internal Simulation][Anritsu][CA_Protocol][TC_4.1.1.20]
 * <saved by Perforce>
 *
 * 10 02 2015 jack.chu
 * [MOLY00131220] [PS6][91plus] Stacktimer to ES migration
 * 	ST to ES: Redesign (LR11 OF)
 *
 * 09 25 2015 james-chi-ju.chang
 * [MOLY00143156] [MT6755][E1][GCF][Anite][3G][FDD][CSG][6.3.1.1] Test Fail
 * .
 *
 * 09 02 2015 wenlong.an
 * [MOLY00125236] 23G PingPong Reselection Restrain - UAS
 * 23G pingpong restrain MD91 porting
 *
 * 08 20 2015 jack.chu
 * [MOLY00137298] [MT6755][E1][FT][FDD][HK][WW FT][Overnight][SIM1: PCCW][Fatal error (task)] err_code1:0x00000C05 err_code2:0x00000001 erro_code3:0xF01CF8DF
 * 	Stacktimer to ES rollback
 * 	.
 *
 * 08 17 2015 nicky.chou
 * [MOLY00117237] DCH SIB collection for CGI reporting to AP
 * .
 *
 * 08 06 2015 cen.chen
 * [MOLY00135754] [UMOLY][3G][TDD][RRCE]Stacktimer to EventScheduler migration.
 *
 * 08 04 2015 jack.chu
 * [MOLY00131220] [PS6][91plus] Stacktimer to ES migration
 * 	.
 *
 * 08 04 2015 nicky.chou
 * [MOLY00131220] [PS6][91plus] Stacktimer to ES migration
 * .
 *
 * 07 06 2015 tereasa.huang
 * [MOLY00107439] [Feature] CSFB duration identification for PCH
 * .
 *
 * 06 21 2015 yuhhwang.yu
 * [MOLY00122048] [6795] Request new feature to improve registration time of roaming case
 * .
 *
 * 06 18 2015 yuhhwang.yu
 * [MOLY00092459] [Denali-1][MT6735][Stage-1][CSFB DSDS][Local FT][India-Delhi] Assert: u11101.c Line:194
 * . RSSI sniffer stop modification
 *
 * 06 17 2015 yuhhwang.yu
 * [MOLY00122058] [CISE][Gemini][L+W] proc sharing
 * .
 *
 * 05 28 2015 yanjuan.feng
 * [MOLY00114769] [Copy CR][Denali-1][MT6735][Stage-1][CSFB DSDS][Local FT][India-Delhi] Assert: u11101.c Line:194
 * .
 *
 * 05 18 2015 yunqi.wang
 * [MOLY00106779] Allowable Registration Area List Feature Check In
 * .
 *
 * 04 29 2015 cen.chen
 * [MOLY00109047] [UMOLY][new feature] Pich false alarm Optimization.
 * LRRCE & RRCE code change for Paging OPT.
 *
 * 04 23 2015 yuhhwang.yu
 * [MOLY00095378] Amazon Requirement
 * . CISE UMOLY part
 *
 * 04 16 2015 elle.sun
 * [MOLY00087788] [Universal Bin] FDD SLCE Check-in
 * 	UBIN Phase2 - set RAT and mode switch.
 *
 * 03 11 2015 dongqing.qi
 * [MOLY00098473] [LMEME/LMOB/L4C] Power Consumption Enhancement for Signal Bar Reporting
 * .
 *
 * 03 11 2015 yenchih.yang
 * [MOLY00098473] [LMEME/LMOB/L4C] Power Consumption Enhancement for Signal Bar Reporting
 * .
 *
 * 03 09 2015 dongqing.qi
 * [MOLY00098139] [TDD][MT6291]LMEME MEME development
 * .add trace and inject msg
 *
 * 01 06 2015 wonder.lee
 * [MOLY00087820] [USIME/MCDDLL] Ubin merge from PA's Ubin  Cbr
 * .
 *
 * 01 06 2015 xinqiu.wang
 * [MOLY00087344] [UMOLY][TDD][UAS]sync U-Bin CBr to UMOLY TRUNCK
 * .
 *
 * 12 29 2014 ethan.han
 * [MOLY00087858] [RRCE] Universal Bin Modification
 * 	Fix misg_id.
 *
 * 12 29 2014 yenchih.yang
 * [MOLY00084256] [MEME] sync MT6291 to UMOLY
 * Remove duplicated URR message ID.
 *
 * 12 26 2014 farming.tseng
 * [MOLY00087857] [UAS FDD] UBIN intra-category interface
 * [UBIN] merge peng-an CBr CL 956838 build error fix.
 *
 * 12 26 2014 farming.tseng
 * [MOLY00087857] [UAS FDD] UBIN intra-category interface
 * [UBIN] sync build error fix to UBIN CBr.
 *
 * 12 23 2014 farming.tseng
 * [MOLY00087857] [UAS FDD] UBIN intra-category interface
 * [UBIN] prefix modification.
 *
 * 12 23 2014 jin.liang
 * [MOLY00087344] [UMOLY][TDD][UAS]sync U-Bin CBr to UMOLY TRUNCK
 * rm duplicate primitive.
 *
 * 12 19 2014 ethan.han
 * [MOLY00087858] [RRCE] Universal Bin Modification
 * 	Fix msg_id.
 *
 * 12 19 2014 farming.tseng
 * [MOLY00087857] [UAS FDD] UBIN intra-category interface
 * [UBIN] prefix error modify.
 *
 * 12 17 2014 james-chi-ju.chang
 * [MOLY00078264] [UMOLY][R10][R11] NAS check-in from CBr to 6291_DEV
 * 	.
 *
 * 12 16 2014 chin-chia.chang
 * [MOLY00087443] [Universal Bin] [FDD] [UAS] [URR/Common] Check-in
 * [UniBin] [UMOLY] [FDD] [UAS] [URR] urr_msgid.h
 *
 * 12 16 2014 ethan.han
 * [MOLY00087858] [RRCE] Universal Bin Modification
 * 	SAP.
 *
 * 12 16 2014 farming.tseng
 * [MOLY00087857] [UAS FDD] UBIN intra-category interface
 * [UAS FDD] CISE msg id.
 *
 * 12 16 2014 wonder.lee
 * [MOLY00087820] [USIME/MCDDLL] Ubin merge from PA's Ubin  Cbr
 * .
 *
 * 12 16 2014 claud.li
 * [MOLY00087795] [MEME] universal bin check in
 * [Universal bin] [FDD][MEME/RRCE/CSCE/CSE/AGPS] interface and message id
 *
 * 12 16 2014 elle.sun
 * [MOLY00087788] [Universal Bin] FDD SLCE Check-in
 * 	.
 *
 * 12 15 2014 jin.liang
 * [MOLY00087491] [UMOLY][TDD][UAS][SLCE/RRCE]sync U-Bin CBr to UMOLY TRUNCK.
 * sync common files.
 *
 * 12 14 2014 stephen.hsu
 * [MOLY00087428] [Universal Bin] FDD ADR Check-in
 *
 * 12 12 2014 nancy.chang
 * [MOLY00087510] [Universal Bin] FDD DBME & LDBME development
 * .
 *
 * 12 12 2014 yuhhwang.yu
 * [MOLY00087211] [CISE] add CSG fingerprint compile option and bug fix
 * . CISE codes
 *
 * 12 12 2014 shaohua.deng
 * [MOLY00087491] [UMOLY][TDD][UAS][SLCE]sync U-Bin CBr to UMOLY TRUNCK.
 * [UMOLY][TDD][UAS][SLCE]sync U-Bin CBr to UMOLY TRUNCK
 * 	sync slce from u-bin.
 *
 * 11 14 2014 yenchih.yang
 * [MOLY00084256] [MEME] sync MT6291 to UMOLY
 * URR/MEME.
 *
 * 11 07 2014 stephen.hsu
 * [MOLY00083543] [UMOLY][ADR] Code Sync from MT6291_DEV to UMOLY main trunk
 *
 * 09 24 2014 wenlong.an
 * [MOLY00079317] [3G TDD][CSCE][CSE][U3G][universal bin] - compile option part
 * compile options remove&rename
 * 	remove __PLMN_LIST_PREF_SUPPORT
 * 	remove __MTK_UL1_FDD__
 * 	__UAGPS_CP_SUPPORT__ -> __TDD__UAGPS_CP_SUPPORT__
 * 	__3G_AUTO_BAND_MECHANISM__ -> __TDD_3G_AUTO_BAND_MECHANISM__ 
 * 	__CSHSPA_SUPPORT__ -> __TDD_CSHSPA_SUPPORT__
 * 	__AGPS_CP_SIB15__ -> __TDD_AGPS_CP_SIB15__
 * 	__TD_NETWORK_SHARING__ -> items in interface with NAS always exit 
 * 	__COMMON_EDCH_SUPPORT__ -> __TDD_COMMON_EDCH_SUPPORT__
 * 	__ENHANCED_COMMON_STATE_SUPPORT__ -> __TDD_ENHANCED_COMMON_STATE_SUPPORT__ 
 * 	__HSDSCH_DRX_CELL_FACH_SUPPORT__ -> __TDD_HSDSCH_DRX_CELL_FACH_SUPPORT__
 * 	__PPACR_SUPPORT__ -> _TDD_PPACR_SUPPORT__
 *
 * 07 02 2014 yanjuan.feng
 * [MOLY00070824] [4G Gemini][FT][BJ][CSFB test][case5.1.1][SIM1 CMCC+SIM2 CMCC][4G,3G,2Gע²?±?¾�]
 * .3G plmn search abort
 *
 * 03 13 2014 xinqiu.wang
 * [MOLY00059440] [3G TDD][UAS][SYNC FDD CR] Add SRB Flow Control to avoid URR Queue Full
 * .
 *
 * 01 22 2014 tereasa.huang
 * [MOLY00054324] [4G Gemini][Merge] MOLY.MM.GEMINI.DEV Merge back to MOLY
 * [FDD][RRCE] Merge LTE Gemini to MOLY
 *
 * 01 17 2014 cen.chen
 * [MOLY00051354] [TDD][RRCE]LTE Gemini development.
 * Modify RRC_Check_ModisIT.
 *
 * 12 20 2013 vend_yuhhwang.yu
 * [MOLY00050818] [CSCE] Code Sync : Customer functions
 * .
 *
 * 11 13 2013 yuguo.xu
 * [MOLY00046226] [CC/MM/RATCM/RRCE]CC_DISCONNECT&Force Release Optimization
 * 	CC_DISCONNEC&Force Release Optimization Mobility Part.
 *
 * 10 21 2013 vend_yuhhwang.yu
 * [MOLY00040050] [MultiMode] Dynamic band selection
 * .
 *
 * 10 21 2013 xinqiu.wang
 * [MOLY00040050] [MultiMode] Dynamic band selection.
 *
 * 09 26 2013 chih-chien.hsu
 * [MOLY00027182] [MT6290E1][W/G][Overnight][Taiwan] Modem warning: [1][68] u11126.c #6538
 * [new][SLCE] Change design of MEME sendgin MC through SLCE to L1.
 *
 * 09 17 2013 peng.hu
 * [MOLY00038199] [Check in][Remove Compile Option]Remove __UMTS_TDD128_SNIFFER__
 * .
 *
 * 07 06 2013 ya.li
 * [MOLY00023642] [Volunteer Patch][3G][SMART PAGING]smart paging optimization for BCCH modification
 * .
 *
 * 06 26 2013 ivy.wang
 * [MOLY00025900] [Volunteer Patch][3G] Improve detection of SIB Change
 * smart paging - reduce possibility of missing bcch modification info
 *
 * 04 22 2013 claud.li
 * [MOLY00020436] [MEME] intra-f, inter-f bug fixed [MEME/UMAC] countC modification with UMAC
 * [MEME] intra-f, inter-f bug fixed [MEME/UMAC] countC modification with UMAC
 *
 * 04 09 2013 ye.yuan
 * [MOLY00013057] [MT7208][NW-UE SIM] [HSPA8][TC 7_3_7_1] Fatal error in MODIS
 * .
 *
 * 04 01 2013 yenchih.yang
 * [MOLY00013057] [MT7208][NW-UE SIM] [HSPA8][TC 7_3_7_1] Fatal error in MODIS
 * .
 *
 * 03 13 2013 c-hua.yang
 * [MOLY00009184] [URR] Multimode Merge to MOLY
 * .
 *
 * 01 30 2013 c-hua.yang
 * [MOLY00009184] [URR] Multimode Merge to MOLY
 * sync MOLY00007401, MOLY00007503, MOLY00004506, MOLY00003486
 *
 * 01 22 2013 c-hua.yang
 * [MOLY00009184] [URR] Multimode Merge to MOLY
 * .
 *
 * 11 28 2012 nicky.chou
 * NULL
 * [CSE] R9MM Modification.
 * 
 * 10 26 2012 xuechao.wang
 * [MOLY00005344] ��MTK6515�������ƶ�Э��һ���Բ��ԡ�MTK U795 Signalling connection release indication procedure�����쳣
 * .
 * 
 * 10 26 2012 xuechao.wang
 * [MOLY00005344] ��MTK6515�������ƶ�Э��һ���Բ��ԡ�MTK U795 Signalling connection release indication procedure�����쳣
 * .
 * 
 * 09 26 2012 yong.su
 * [MOLY00004143] [PSS5]TDD_R9_DEV Patch back to MOLY
 * Change filetype
 * 
 * 09 26 2012 ye.yuan
 * [MOLY00004173] [3G TDD][CISE]R9 code merge back to MOLY
 * CSCE CODE Interface part .
 * 
 * 09 14 2012 peng.hu
 * [MOLY00003486] [Vodafone Operator Test] make an Emergency Call on Intra-frequency restricted cells
 * .
 * 
 * 09 14 2012 peng.hu
 * [MOLY00003486] [Vodafone Operator Test] make an Emergency Call on Intra-frequency restricted cells
 * .
 * 
 * 08 23 2012 ya.li
 * [MOLY00002550] [Athens17][CMCC Package][CMCC TD FT][Guangzhou][2 round-1 time][2.1��������š����Ų���]25th_10��23_��ʱ�޷���ͨ
 * .
 * 
 * 08 10 2012 maruco.tu
 * [MOLY00001700] [Inter-RAT] Correct IRCCO cause in RCR and remove unused msg_id
 * [MOLY00001700]
 * 
 * 08 09 2012 maruco.tu
 * [MOLY00001700] [Inter-RAT] Correct IRCCO cause in RCR and remove unused msg_id
 * [Inter-RAT] Correct IRCCO cause in RCR and remove unused msg_id.
 *
 * 06 27 2012 ye.yuan
 * [MOLY00000029] [3G TDD]modify msg id range in MOLY branch
 * USIME/CSE/CSCE/MEME/ADR/URR.
 *
 * 06 25 2012 yong.su
 * [MOLY00000029] [3G TDD]modify msg id range in MOLY branch
 * .
 *
 * 06 12 2012 qinghua.yu
 * removed!
 * .
 *
 * 06 11 2012 qinghua.yu
 * removed!
 * .
 *
 * 05 29 2012 austin.tsai
 * removed!
 * .
 *
 * 05 25 2012 yj.cheng
 * removed!
 * .
 *
 * 05 24 2012 wcpuser_integrator
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * 05 24 2012 wcpuser_integrator
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * 05 24 2012 wcpuser_integrator
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * 05 06 2012 changchun.zhang
 * removed!
 * .
 *
 * 05 04 2012 hongwei.zhang
 * removed!
 * : merge sniffer sap.
 *
 * 04 11 2012 babylon.tien
 * removed!
 * <saved by Perforce>
 *
 * 04 10 2012 chi-chung.lin
 * removed!
 * [MT6280] code sync. from MT6280_DVT_DEV to MT6280_GCC_DEV
 *
 * 01 16 2012 yenchih.yang
 * removed!
 *
 * 01 12 2012 mark.ng
 * removed!
 * TK6280 code to MT6280_DVT_DEV
 *
 * 01 11 2012 shunwen.hsiao
 * removed!
 * Check in TK6280_DVT_DEV to MT6280_DVT_DEV
 *
 * 01 09 2012 nienteh.hsu
 * removed!
 * .
 *
 * 01 06 2012 chi-chung.lin
 * removed!
 * .
 *
 * 12 11 2011 haizhou.liu
 * removed!
 * .
 *
 * 11 23 2011 yenchih.yang
 * removed!
 * .
 *
 * 11 15 2011 ye.yuan
 * removed!
 * fix build error.
 *
 * 11 11 2011 xuechao.wang
 * removed!
 * .
 *
 * 11 10 2011 haizhou.liu
 * removed!
 * .
 *
 * 11 10 2011 yongtuan.qiao
 * removed!
 * modify for urr_sap.
 *
 * 08 28 2011 nicky.chou
 * removed!
 * .
 *
 * 06 21 2011 yenchih.yang
 * removed!
 * Rollback //MAUI/TRUNK/MAUI/mcu/uas/interfaces/sap/urr_sap.h to revision 14
 *
 * 05 24 2011 mw.hsu
 * removed!
 * .
 *
 * 04 15 2011 dennis.weng
 * removed!
 * .
 *
 * 03 18 2011 jd.ni
 * removed!
 * check in Fast Dormancy RRCE part.
 *
 * 03 16 2011 jessica.chang
 * removed!
 * MAUI_02622100: [MT6276][3G Gemini][UMAC] Gemini 2.0 check-in
 *
 * 03 16 2011 alvin.chen
 * removed!
 * .
 *
 * 03 16 2011 mw.hsu
 * removed!
 * .
 *
 * 12 23 2010 jd.ni
 * removed!
 * .
 *
 * 12 15 2010 dennis.weng
 * removed!
 * Rollback Gemini+ modification for TDD
 *
 * 12 09 2010 william.chang
 * removed!
 * .
 *
 * 12 09 2010 william.chang
 * removed!
 * .
 *
 * 12 09 2010 william.chang
 * removed!
 * .
 *
 * 12 09 2010 william.chang
 * removed!
 * .
 *
 * 12 07 2010 maruco.tu
 * removed!
 * .
 *
 * 12 01 2010 peng.pan
 * removed!
 * Remove version 19.
 *
 * 12 01 2010 quanping.wang
 * removed!
 * Merge TDD128 backto MAUI, based on 10AW1032MP_ASTRO w10.48 Tue. P1
 *
 * 11 30 2010 peng.pan
 * removed!
 * TDD 10A sync to MAUI.
 *
 * 10 30 2010 george.chang
 * removed!
 * .
 *
 * 10 11 2010 dennis.weng
 * removed!
 * .
 *
 * 08 06 2010 mw.hsu
 * removed!
 * .
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * SIB3/4 Change Indication for MEME
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * CSCE handles REGN_STATUS_UPDATE_REQ from RATCM instead of from RRCE.
 *
 * removed!
 * removed!
 * Message for MEME to notify CSCE Change of reference cell in DCH
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 1. Added New Cell Reselection Mechanism.
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * add to source control recursely
 *===========================================================================
 ****************************************************************************/
#include "module_msg_range.h"

#ifndef _URR_MSG_H
#define _URR_MSG_H

#ifdef __SOURCE_INSIGHT_PARSE__
typedef enum {
#endif

/* mtk80197, merge TDD128 back to MAUI */
#if defined(__UMTS_FDD_MODE__)
MODULE_MSG_BEGIN( MSG_ID_FDD_ADR_CODE_BEGIN )
//MSG_ID_FDD_ADR_CODE_BEGIN,
MSG_ID_FDD_RLC_TM_DATA_IND = MSG_ID_FDD_ADR_CODE_BEGIN,
MSG_ID_FDD_RLC_UM_DATA_IND,
MSG_ID_FDD_RLC_AM_DATA_IND,

#ifdef UNIT_TEST
MSG_ID_FDD_ADR_UNPACK_UT_EVENT_PHY_DATA_IND,
MSG_ID_FDD_ADR_UNPACK_UT_EVENT_RLC_DATA_IND,
MSG_ID_FDD_ADR_UNPACK_UT_EVENT_VERDICT_DATA_IND,
MSG_ID_FDD_ADR_PACK_UT_MOVE_TO_IDLE_REQ,
MSG_ID_FDD_ADR_PACK_UT_SEND_CCCH_REQ,
MSG_ID_FDD_ADR_PACK_UT_SEND_DCCH_REQ,
#endif

MSG_ID_FDD_ADR_ADR_ACKNOWLEDGEMENT_IND,
MSG_ID_FDD_RLC_AM_DATA_CNF,
MSG_ID_FDD_ADR_CODE_END = MSG_ID_FDD_RLC_AM_DATA_CNF,
//MSG_ID_FDD_ADR_CODE_END,
MODULE_MSG_END( MSG_ID_FDD_ADR_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_FDD_CSCE_CODE_BEGIN )
//MSG_ID_CSCE_CODE_BEGIN,
//SLCE
MSG_ID_FDD_URR_SLCE_SET_ACTIVE_RAT_CNF = MSG_ID_FDD_CSCE_CODE_BEGIN,  /*Alfie: this msg_id is also used by RRCE*/
MSG_ID_FDD_CSCE_SLCE_INITIALISE_CNF,
MSG_ID_FDD_CSCE_SLCE_RF_ON_CNF,
MSG_ID_FDD_CSCE_SLCE_RF_OFF_CNF,
MSG_ID_FDD_CSCE_SLCE_RSSI_SNIFFER_STOP_CNF,

//RRCE
MSG_ID_FDD_CSCE_RRCE_MOVE_TO_IDLE_IND,
MSG_ID_FDD_CSCE_RRCE_MOVE_TO_CELL_DCH_IND,
MSG_ID_FDD_CSCE_RRCE_MOVE_TO_CONNECTED_IND,
MSG_ID_FDD_CSCE_RRCE_MOVE_TO_INACTIVE_IND,
MSG_ID_FDD_CSCE_RRCE_BCCH_MODIFICATION_INFO_IND,
MSG_ID_FDD_CSCE_RRCE_RRC_CONNECTION_ESTABLISHMENT_IND,
MSG_ID_FDD_CSCE_RRCE_RELEASE_CHANNELS_CNF,
MSG_ID_FDD_CSCE_RRCE_OUT_OF_SERVICE_AREA_CNF,
MSG_ID_FDD_RRCE_CSCE_SIB_COLLECTION_RSP,
MSG_ID_FDD_CSCE_RRCE_STEADY_INACTIVE_IND,

MSG_ID_FDD_RRCE_CSCE_DCH_SIB_COLLECTION_START_REQ,
MSG_ID_FDD_RRCE_CSCE_DCH_SIB_COLLECTION_STOP_REQ,

#ifdef __GEMINI_PREEMPT_PEER_SERVICE__
MSG_ID_FDD_CSCE_RRCE_ABORT_SERVICE_REQ,
MSG_ID_FDD_CSCE_RRCE_ABORT_SERVICE_COMPLETE_IND,
#endif

#ifdef __SMART_PAGING_3G_FDD__
MSG_ID_FDD_CSCE_RRCE_SMART_PAGING_STATUS_IND,
#endif

#if defined(__23G_PRI_RESEL_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_FDD_RRCE_CSCE_DEDI_PRIO_INFO_IND,
#endif

//CSE
MSG_ID_FDD_CSCE_CSE_CELL_SELECTION_STOP_CNF, 
MSG_ID_FDD_CSCE_CSE_CELL_SELECTION_CNF, 
MSG_ID_FDD_CSCE_CSE_PLMN_LIST_CNF, 
MSG_ID_FDD_CSCE_CSE_FREQ_SCAN_SUSPEND_IND, 
#if defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_FDD_CSCE_CSE_FINGERPRINT_COLLECTION_CNF,
MSG_ID_FDD_CSCE_CSE_FINGERPRINT_COLLECTION_STOP_CNF,
#endif
#if defined(__GEMINI_WCDMA__) && defined(__UAS_GEMINI_PROC_SHARING__)
MSG_ID_FDD_CSCE_CSE_VIRTUAL_CELL_SELECTION_CNF,
MSG_ID_FDD_CSCE_CSE_VIRTUAL_PLMN_LIST_CNF, 
#endif

#ifdef __WCDMA_PREFERRED__
MSG_ID_FDD_CSCE_CSE_DETECT_CELL_SEARCH_SUSPEND_CNF,
MSG_ID_FDD_CSCE_CSE_DETECT_CELL_SEARCH_CNF,
#endif

#if defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_FDD_CSCE_CSE_CSG_LIST_CNF,
MSG_ID_FDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_SUSPEND_CNF,
MSG_ID_FDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_CNF,
MSG_ID_FDD_MEME_CSE_CSG_AUTONOMOUS_SEARCH_INTRA_FREQ_CELL_IND,
MSG_ID_FDD_CSCE_CSE_EVALUATE_CSG_CELL_CNF,
MSG_ID_FDD_CSCE_CSE_EVALUATE_CSG_CELL_SUSPEND_CNF,
#endif

#ifdef __LTE_RAT__
MSG_ID_FDD_CSCE_CSE_CGI_COLLECTION_CNF,
MSG_ID_FDD_CSCE_CSE_CGI_COLLECTION_STOP_CNF,
#endif /* __LTE_RAT__ */

//SIBE
MSG_ID_FDD_SIBE_SIB_COLLECTION_CNF, 
MSG_ID_FDD_SIBE_SIB_MONITORING_CNF, 
MSG_ID_FDD_SIBE_SIB_MONITORING_ERROR_IND, 
//MEME
MSG_ID_FDD_CSCE_MEME_CELL_MEASUREMENT_RESULT_IND,
MSG_ID_FDD_CSCE_MEME_LTE_MEASUREMENT_IND,
MSG_ID_FDD_CSCE_MEME_CELL_REF_TIME_ANCHOR_IND,
MSG_ID_FDD_MEME_CSCE_MODIFY_CELL_LIST_IND,
MSG_ID_FDD_CSCE_MEME_REF_CELL_CHANGE_IND,
MSG_ID_FDD_CSCE_MEME_EUTRA_FACH_MC_NOTIFICATION,

//USIME
MSG_ID_FDD_CSCE_USIME_USIM_REMOVED_IND,
MSG_ID_FDD_CSCE_USIME_READ_NVRAM_CNF,
MSG_ID_FDD_USIME_SIM_FILE_CHANGE_IND,

//RATCM
MSG_ID_RATCM_CSCE_INIT_REQ,
MSG_ID_RATCM_CSCE_PLMN_SEARCH_REQ,
MSG_ID_RATCM_CSCE_PLMN_LIST_REQ,
MSG_ID_RATCM_CSCE_PLMN_LIST_STOP_REQ,
MSG_ID_RATCM_CSCE_PLMN_LIST_ABORT_REQ,
MSG_ID_RATCM_CSCE_ADD_FORBIDDEN_LA_REQ,
MSG_ID_RATCM_CSCE_DEL_FORBIDDEN_LA_REQ,
MSG_ID_RATCM_CSCE_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_RATCM_CSCE_HPLMN_INFO_UPDATE_REQ,
MSG_ID_RATCM_CSCE_RRC_DEACTIVATE_REQ,
MSG_ID_RATCM_CSCE_SET_RAT_MODE_REQ,
MSG_ID_RATCM_CSCE_RFON_REQ,
MSG_ID_RATCM_CSCE_RFOFF_REQ,
MSG_ID_RATCM_CSCE_SET_IMEI_REQ,
MSG_ID_RATCM_CSCE_CLEAR_MRU_REQ,
MSG_ID_RATCM_CSCE_SET_MRU_REQ,
MSG_ID_RATCM_CSCE_CSG_AUTO_SEARCH_MODE_REQ,
MSG_ID_RATCM_CSCE_EMC_SESSION_START_REQ,
MSG_ID_RATCM_CSCE_EMC_SESSION_STOP_REQ,
MSG_ID_RATCM_CSCE_EMC_FORBIDDEN_NW_LIST_UPDATE_REQ,

//CM
MSG_ID_CMCSCE_EMERGENCY_CALL_STATUS_IND,

#ifdef __GEMINI__
MSG_ID_RATCM_CSCE_SIM_STATUS_UPDATE_REQ,
#endif

#if defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_RATCM_CSCE_CSG_LIST_REQ,
MSG_ID_RATCM_CSCE_CSG_LIST_STOP_REQ,
MSG_ID_RATCM_CSCE_UPDATE_WHITE_LIST_REQ,
#endif

#ifdef __LTE_RAT__
MSG_ID_RATCM_UAS_RAT_CHANGE_REQ,  //also used by RRCE
MSG_ID_RATCM_CSCE_EUTRAN_CAP_UPDATE_REQ,
#endif

MSG_ID_RATCM_CSCE_REGN_STATUS_UPDATE_REQ,
MSG_ID_RATCM_CSCE_PLMN_LIST_STATUS_UPDATE_REQ,
MSG_ID_FDD_CSCE_CODE_END = MSG_ID_RATCM_CSCE_REGN_STATUS_UPDATE_REQ, 
//MSG_ID_CSCE_CODE_END,
MODULE_MSG_END( MSG_ID_FDD_CSCE_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_FDD_CSE_CODE_BEGIN )
//MSG_ID_CSE_CODE_BEGIN,
//SLCE
MSG_ID_FDD_CSE_SLCE_FREQ_SCAN_SUSPEND_IND = MSG_ID_FDD_CSE_CODE_BEGIN,
// MEME
MSG_ID_FDD_CSE_MEME_CELL_MEASUREMENT_RESULT_IND,
// CSCE
MSG_ID_FDD_CSCE_CSE_CELL_SELECTION_START_REQ, 
MSG_ID_FDD_CSCE_CSE_CELL_SELECTION_STOP_REQ, 
MSG_ID_FDD_CSCE_CSE_PLMN_LIST_START_REQ, 
MSG_ID_FDD_CSCE_CSE_PLMN_LIST_SUSPEND_REQ, 
MSG_ID_FDD_CSCE_CSE_RF_OFF_REQ,                             // For auto band
MSG_ID_FDD_CSCE_CSE_PLMN_LOSS_WITH_LIST_IND,                // For PLMN List optimization
#if defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_FDD_CSCE_CSE_FINGERPRINT_COLLECTION_REQ,
MSG_ID_FDD_CSCE_CSE_FINGERPRINT_COLLECTION_STOP_REQ,
#endif
MSG_ID_FDD_CSE_SLCE_FREQ_SCAN_CNF,

#ifdef __WCDMA_PREFERRED__
MSG_ID_FDD_CSCE_CSE_DETECT_CELL_SEARCH_START_REQ,
MSG_ID_FDD_CSCE_CSE_DETECT_CELL_SEARCH_SUSPEND_REQ,
#endif

#if (defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__))
MSG_ID_FDD_CSCE_CSE_CSG_LIST_START_REQ,
MSG_ID_FDD_CSCE_CSE_CSG_LIST_SUSPEND_REQ,
MSG_ID_FDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_START_REQ,
MSG_ID_FDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_SUSPEND_REQ,
MSG_ID_FDD_CSCE_CSE_EVALUATE_CSG_CELL_REQ,
MSG_ID_FDD_CSCE_CSE_EVALUATE_CSG_CELL_SUSPEND_REQ,
#endif

#ifdef __LTE_RAT__
MSG_ID_FDD_CSCE_CSE_CGI_COLLECTION_REQ,
MSG_ID_FDD_CSCE_CSE_CGI_COLLECTION_STOP_REQ,
#endif
MSG_ID_FDD_CSCE_CSE_PLMN_LIST_STATUS_UPDATE_REQ,

MSG_ID_FDD_CSE_CACHE_INFO_IND,                              // For showing cache content to Catcher...>#I
MSG_ID_FDD_CSE_CODE_END = MSG_ID_FDD_CSE_CACHE_INFO_IND, 
MODULE_MSG_END( MSG_ID_FDD_CSE_CODE_TAIL )
//MSG_ID_CSE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_FDD_MEME_CODE_BEGIN )
//MSG_ID_FDD_MEME_CODE_BEGIN,
//SLCE
//UMAC
MSG_ID_FDD_MEME_UMAC_TRAFFIC_VOLUME_MEASUREMENT_IND = MSG_ID_FDD_MEME_CODE_BEGIN,
MSG_ID_FDD_MEME_UMAC_QUALITY_MEASUREMENT_IND,
MSG_ID_FDD_MEME_UMAC_ADDITIONAL_TVM_IND,
MSG_ID_FDD_MEME_UMAC_MEASUREMENT_ERROR_IND,
#ifdef __UMTS_R6__
MSG_ID_FDD_MEME_UMAC_TVM_EXCEED_THRESHOLD_IND,
#endif
MSG_ID_FDD_MEME_UMAC_COUNTC_STATUS_IND,
//RRCE
MSG_ID_FDD_RRCE_MEME_MOVE_TO_STATE_REQ,
MSG_ID_FDD_MEME_RRCE_COMPRESSED_MODE_RECONFIGURE_FAILURE_IND,
MSG_ID_FDD_MEME_RRCE_COMPRESSED_MODE_RECONFIGURE_SUCCESS_IND,
MSG_ID_FDD_RRCE_MEME_ASU_IND,

//SLCE
MSG_ID_FDD_MEME_SLCE_SUSPEND_REPORT_IND,
MSG_ID_FDD_MEME_SLCE_RESUME_REPORT_IND,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_CELL_CNF,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_TGPS_CNF,


//CSCE
MSG_ID_FDD_CSCE_MEME_INITIALISE_REQ,
MSG_ID_FDD_MEME_CSCE_CELL_SELECTED_IND,
MSG_ID_FDD_CSCE_MEME_MEAS_MANIPULATION_REQ,
MSG_ID_FDD_CSCE_MEME_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_FDD_CSCE_MEME_RF_ON_REQ,
MSG_ID_FDD_CSCE_MEME_RF_OFF_REQ,
MSG_ID_FDD_CSCE_MEME_SET_MODE_REQ,
MSG_ID_FDD_CSCE_MEME_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_FDD_CSCE_MEME_CLEAN_DB_CELL_REQ,
MSG_ID_FDD_CSCE_MEME_SIB19_CHANGE_IND,
//SIBE
MSG_ID_FDD_MEME_SIBE_SIB3_CHANGE_IND,
MSG_ID_FDD_MEME_SIBE_SIB4_CHANGE_IND,
MSG_ID_FDD_MEME_SIBE_SIB11_CHANGE_IND, 
MSG_ID_FDD_MEME_SIBE_SIB12_CHANGE_IND, 
MSG_ID_FDD_MEME_SIBE_SIB18_CHANGE_IND, 
//MEME self
MSG_ID_FDD_MEME_MEME_QUEUED_GAS_UAS_CONFIG_UCELL_MEAS_REQ,
MSG_ID_FDD_MEME_MEME_QUEUED_GAS_UAS_CONFIG_UCELL_PRIO_MEAS_REQ,
MSG_ID_FDD_MEME_MEME_QUEUED_EAS_UAS_CONFIG_UCELL_MEAS_REQ,
MSG_ID_FDD_MEME_MEME_QUEUED_EAS_UAS_CONFIG_UCELL_PRIO_MEAS_REQ,
MSG_ID_FDD_MEME_MEME_SAVED_MEAS_CTRL_IND,
MSG_ID_FDD_MEME_NBR_CELL_INFO_IND,
MSG_ID_FDD_MEME_CELL_POWER_LEVEL_IND,
MSG_ID_FDD_MEME_DUMP_CONTEXT,
MSG_ID_FDD_MEME_UT_SET_CONTEXT,
MSG_ID_FDD_MEME_UT_SET_SHM,


MSG_ID_FDD_MEME_CODE_END = MSG_ID_FDD_MEME_UT_SET_SHM,
MODULE_MSG_END( MSG_ID_FDD_MEME_CODE_TAIL )
//MSG_ID_FDD_MEME_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_FDD_RRCE_CODE_BEGIN )
//MSG_ID_FDD_RRCE_CODE_BEGIN,
//UDC
MSG_ID_RATCM_RRCE_CONN_EST_REQ = MSG_ID_FDD_RRCE_CODE_BEGIN,
MSG_ID_RATCM_RRCE_CONN_REL_REQ,
MSG_ID_RATCM_RRCE_CONN_ABORT_REQ,
MSG_ID_RATCM_RRCE_DATA_TRANSFER_REQ,
MSG_ID_RATCM_RRCE_SECURITY_MODE_REQ,
MSG_ID_RATCM_RRCE_RB_RE_ESTABLISHMENT_RSP,
//UNT
MSG_ID_RATCM_RRCE_PAGING_PARAM_ASSIGN_REQ,
//NEW
MSG_ID_RATCM_RRCE_REGN_STATUS_UPDATE_REQ,
#ifdef __GEMINI__
MSG_ID_RATCM_RRCE_NO_IR_SIG_PROC_REQ,
#endif
#ifdef __NO_PSDATA_SEND_SCRI__
MSG_ID_RATCM_RRCE_END_PS_DATA_SESSION_REQ,
#endif
#ifdef __FAST_DORMANCY__
MSG_ID_RATCM_RRCE_END_PS_DATA_SESSION_REQ,
#endif
#ifdef __LTE_RAT__
MSG_ID_RATCM_UAS_RAT_CHANGE_RES,
//LTE interRAT
MSG_ID_RATCM_RRCE_RAT_CHANGE_REQ,
MSG_ID_RATCM_RRCE_RAT_CHANGE_RSP,
MSG_ID_RATCM_CSCE_RAT_CHANGE_REQ,
MSG_ID_RATCM_UAS_RAT_CHANGE_RSP,
MSG_ID_RATCM_RRCE_CS_STATUS_UPDATE_REQ,
#endif

/* BMC */
MSG_ID_FDD_RRCE_BMC_RX_IND,
MSG_ID_FDD_RRCE_BMC_ETWS_IND,
/* URLC */
MSG_ID_FDD_RRCE_URLC_STATUS_IND,
/* PDCP */
MSG_ID_FDD_RRCE_PDCP_STATUS_IND,

//SLCE
MSG_ID_FDD_RRCE_SLCE_RECONFIG_COMPLETE_IND,
MSG_ID_FDD_RRCE_SLCE_RECONFIG_ERROR_IND,
MSG_ID_FDD_RRCE_SLCE_PDCP_RELOC_IND,
MSG_ID_FDD_RRCE_SLCE_GET_COUNT_C_CNF,
MSG_ID_FDD_RRCE_SLCE_ABORT_CNF,
#if 0
/* under construction !*/
/* under construction !*/
#endif
MSG_ID_FDD_RRCE_SLCE_L1_CONTAINER_RECEIVED_IND,
MSG_ID_FDD_RRCE_SLCE_MONITOR_ORDER_REQ,  
//SIBE
MSG_ID_FDD_RRCE_SIBE_CELL_RST_CNF, 
MSG_ID_FDD_RRCE_SIBE_CELL_RST_STOP_CNF,
//CSCE
MSG_ID_FDD_CSCE_RRCE_SUITABLE_CELL_SELECTED_REQ,
MSG_ID_FDD_CSCE_RRCE_ACCEPTABLE_CELL_SELECTED_REQ,
MSG_ID_FDD_CSCE_RRCE_OUT_OF_SERVICE_AREA_REQ,
MSG_ID_FDD_CSCE_RRCE_DEACTIVATE_REQ,
MSG_ID_FDD_CSCE_RRCE_SET_MODE_REQ,
MSG_ID_FDD_RRCE_CSCE_SIB_COLLECTION_IND,
MSG_ID_FDD_CSCE_RRCE_PCH_TO_FACH_READY_RSP,
MSG_ID_FDD_CSCE_RRCE_RELEASE_CHANNELS_REQ,
//MEME
MSG_ID_FDD_MEME_RRCE_COMPRESSED_MODE_RECONFIGURE_REQ,
MSG_ID_FDD_MEME_RRCE_MONITOR_ORDER_IND,  
//UMAC
MSG_ID_FDD_RRCE_UMAC_STATUS_DATA_PENDING_IND,
MSG_ID_FDD_RRCE_UMAC_STATUS_RACH_IND,
#ifdef __UMTS_R7__
MSG_ID_FDD_RRCE_UMAC_D_HRNTI_DETECTED_IND,
#endif
#ifdef __MTK_INTERNAL__
// RRCE itself
MSG_ID_FDD_RRCE_RRCE_DEBUG_INFO_IND,
#endif
/* ACK */
MSG_ID_FDD_RRCE_RRCE_SECURITY_ACK_IND,//Jingo: R10CR 4427
MSG_ID_FDD_RRCL_RRC_ACKNOWLEDGEMENT_IND,
MSG_ID_FDD_RRCE_VERDICT_TIMERID_IND, //Jack: Event Scheduler
MSG_ID_FDD_RRCE_FORCE_TIMER_EXPIRY_IND, //Jack: Event Scheduler
#ifdef __TC7__CS__SUPPORT__
MSG_ID_FDD_RRCE_URLC_USR_DATA_AVAILABLE_CNF,
#endif
MSG_ID_RATCM_UAS_GEMINI_PS_HIGH_SEM_REQ,
MSG_ID_FDD_RRCE_CODE_END = MSG_ID_RATCM_UAS_GEMINI_PS_HIGH_SEM_REQ,
MODULE_MSG_END( MSG_ID_FDD_RRCE_CODE_TAIL )
//MSG_ID_RRCE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_FDD_SIBE_CODE_BEGIN )

//MSG_ID_SIBE_CODE_BEGIN,
//SLCE
MSG_ID_FDD_SIBE_SLCE_CONFIGURE_BCH_FAILED_IND = MSG_ID_FDD_SIBE_CODE_BEGIN,
#ifdef __GEMINI_MONITOR_PAGE_DURING_TRANSFER__
MSG_ID_FDD_SIBE_SLCE_RECONFIGURE_BCH_CNF,
#endif
// SIBE self
MSG_ID_FDD_SIBE_SIB_COLLECTION_REQ, 
MSG_ID_FDD_SIBE_SIB_COLLECTION_CANCEL_REQ, 
MSG_ID_FDD_SIBE_START_SIB_MONITORING_REQ, 
MSG_ID_FDD_SIBE_STOP_SIB_MONITORING_REQ, 
MSG_ID_FDD_RRCE_SIBE_CELL_RST_REQ, 
MSG_ID_FDD_RRCE_SIBE_CELL_RST_STOP_REQ,
#ifdef __UMTS_R8__
MSG_ID_FDD_RRCE_SIBE_SIB7_EXPIRY_TIMER_IND,
#endif
MSG_ID_FDD_CSCE_SIBE_MOVE_TO_IDLE_REQ, 
MSG_ID_FDD_SIBE_DUMP_BCH_SIB_IND,
MSG_ID_FDD_SIBE_SIB_CHANGE_IND,
MSG_ID_FDD_SIBE_CODE_END = MSG_ID_FDD_SIBE_SIB_CHANGE_IND,
MODULE_MSG_END( MSG_ID_FDD_SIBE_CODE_TAIL )
//MSG_ID_SIBE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_FDD_SLCE_CODE_BEGIN )

//MSG_ID_FDD_SLCE_CODE_BEGIN,
//RATCM
MSG_ID_RATCM_SLCE_MONITORING_CLOSE_LOOP_REQ = MSG_ID_FDD_SLCE_CODE_BEGIN,
MSG_ID_RATCM_SLCE_DUPLEX_MODE_CHANGE_REQ,

/* RABM */
MSG_ID_FDD_CRABM_RAB_ESTABLISH_RSP,
MSG_ID_FDD_CRABM_RAB_RELEASE_RSP,
/* PDCP */
MSG_ID_FDD_CPDCP_CONFIG_CNF,
MSG_ID_FDD_CPDCP_RELOC_CNF,
MSG_ID_FDD_CPDCP_RELEASE_CNF,
/* URLC */
MSG_ID_FDD_CRLC_CONFIG_RAB_CNF,
MSG_ID_FDD_CRLC_CONFIG_TM_ESTABLISH_CNF,
MSG_ID_FDD_CRLC_CONFIG_UM_ESTABLISH_CNF,
MSG_ID_FDD_CRLC_CONFIG_AM_ESTABLISH_CNF,
MSG_ID_FDD_CRLC_CONFIG_RELEASE_CNF,
MSG_ID_FDD_CRLC_SUSPEND_CNF,
MSG_ID_FDD_CRLC_RESUME_CNF,
MSG_ID_FDD_CRLC_CONFIG_TX_CIPHERING_CNF,
MSG_ID_FDD_CRLC_CONFIG_RX_CIPHERING_CNF,
MSG_ID_FDD_CRLC_COUNT_C_CNF,
MSG_ID_FDD_CRLC_REESTABLISH_CNF,
/* SEQ */
MSG_ID_FDD_CSEQ_CONFIG_UL2ACC_CLK_ON_INFO_CNF,
MSG_ID_FDD_CSEQ_CONFIG_UL2ACC_CLK_OFF_INFO_CNF,
//CSCE
MSG_ID_FDD_CSCE_SLCE_INITIALISE_REQ,
MSG_ID_FDD_CSCE_SLCE_RF_OFF_REQ,
MSG_ID_FDD_CSCE_SLCE_RF_ON_REQ,
MSG_ID_FDD_CSCE_SLCE_RSSI_SNIFFER_START_REQ,
MSG_ID_FDD_CSCE_SLCE_RSSI_SNIFFER_STOP_REQ,
MSG_ID_FDD_CSCE_SLCE_RSSI_SNIFFER_STOP_IND,
#ifdef __GEMINI__
MSG_ID_FDD_CSCE_SLCE_RESUME_REQ,
#endif

//URR
MSG_ID_FDD_URR_SLCE_SET_ACTIVE_RAT_REQ,
//RRCE
MSG_ID_FDD_RRCE_SLCE_ABORT_REQ,
MSG_ID_FDD_RRCE_SLCE_GET_COUNT_C_REQ,
MSG_ID_FDD_RRCE_SLCE_RECONFIG_REQ,
//SIBE
MSG_ID_FDD_SIBE_SLCE_RECONFIGURE_BCH_REQ,
MSG_ID_FDD_SIBE_SLCE_SIB7_CHANGE_IND,
//CSE
MSG_ID_FDD_CSE_SLCE_FREQ_SCAN_CONTINUE_REQ,
MSG_ID_FDD_CSE_SLCE_FREQ_SCAN_REQ,
MSG_ID_FDD_CSE_SLCE_FREQ_SCAN_SUSPEND_REQ,
MSG_ID_FDD_CSE_SLCE_SPECIFIC_CELL_SEARCH_REQ,
MSG_ID_FDD_CSE_SLCE_SPECIFIC_CELL_SEARCH_STOP_REQ,
//MEME
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_CELL_REQ,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_FMO_REQ,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_TGPS_REQ,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_RSSI_EVENT_REQ,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_TX_POWER_REQ,
MSG_ID_FDD_MEME_SLCE_MEASUREMENT_CONFIG_TX_POWER_STOP_REQ,
MSG_ID_FDD_MEME_SLCE_TX_POWER_RESULT_REQ,
MSG_ID_FDD_MEME_SLCE_RLC_CONTINUE_REQ,
MSG_ID_FDD_MEME_SLCE_RLC_STOP_REQ,                 

//SEQ
MSG_ID_FDD_SEQ_SEQUENCE_REQ,
MSG_ID_FDD_SEQ_SEQUENCE_CONFIRMED_IND,
MSG_ID_FDD_SEQ_SEQUENCE_INDICATED_IND,
MSG_ID_FDD_SEQ_SEQUENCE_ERROR_IND,

//UMAC
MSG_ID_FDD_CMAC_CONFIG_UE_CNF,
MSG_ID_FDD_CMAC_CONFIG_UE_IND,
MSG_ID_FDD_CMAC_CONFIG_TX_CCTRCH_CNF,
MSG_ID_FDD_CMAC_CONFIG_EDCH_CCTRCH_CNF,
MSG_ID_FDD_CMAC_CONFIG_TX_CCTRCH_IND,
MSG_ID_FDD_CMAC_CONFIG_EDCH_CCTRCH_IND,
MSG_ID_FDD_CMAC_REMOVE_TX_CCTRCH_CNF,
MSG_ID_FDD_CMAC_REMOVE_EDCH_CCTRCH_CNF,
MSG_ID_FDD_CMAC_REMOVE_TX_CCTRCH_IND,
MSG_ID_FDD_CMAC_REMOVE_EDCH_CCTRCH_IND,
MSG_ID_FDD_CMAC_CONFIG_RX_CCTRCH_CNF,
MSG_ID_FDD_CMAC_CONFIG_HSDSCH_CCTRCH_CNF,
MSG_ID_FDD_CMAC_CONFIG_RX_CCTRCH_IND,
MSG_ID_FDD_CMAC_CONFIG_HSDSCH_CCTRCH_IND,
MSG_ID_FDD_CMAC_REMOVE_RX_CCTRCH_CNF,
MSG_ID_FDD_CMAC_REMOVE_HSDSCH_CCTRCH_CNF,
MSG_ID_FDD_CMAC_REMOVE_RX_CCTRCH_IND,
MSG_ID_FDD_CMAC_REMOVE_HSDSCH_CCTRCH_IND,
MSG_ID_FDD_CMAC_CONFIG_RACH_CNF,
MSG_ID_FDD_CMAC_CONFIG_RACH_IND,
MSG_ID_FDD_CMAC_CONFIG_CPCH_CNF,
MSG_ID_FDD_CMAC_CONFIG_CIPHERING_CNF,
MSG_ID_FDD_CMAC_COUNT_C_CNF,
MSG_ID_FDD_CMAC_DELETE_CIPHERING_CNF,

MSG_ID_FDD_CMAC_CONFIG_TX_RLC_REESTABLISH_CNF,
MSG_ID_FDD_CMAC_CONFIG_TX_RLC_REESTABLISH_IND,
MSG_ID_FDD_CMAC_CONFIG_RX_RLC_REESTABLISH_CNF,
MSG_ID_FDD_CMAC_CONFIG_RX_RLC_REESTABLISH_IND,

MSG_ID_FDD_CMAC_CONFIG_ABORT_CNF,
MSG_ID_FDD_CMAC_CONFIG_TFC_SUBSET_CNF,
MSG_ID_FDD_CMAC_CONFIG_TFC_SUBSET_IND,
MSG_ID_FDD_CMAC_ABORT_IND,
MSG_ID_FDD_SLCE_CODE_END = MSG_ID_FDD_CMAC_ABORT_IND,
MODULE_MSG_END( MSG_ID_FDD_SLCE_CODE_TAIL )
//MSG_ID_SLCE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_FDD_DBME_CODE_BEGIN )
//MSG_ID_DBME_CODE_BEGIN,
MSG_ID_FDD_DBME_DUMP_IND = MSG_ID_FDD_DBME_CODE_BEGIN,
MSG_ID_FDD_DBME_DUMP_EXT_QUEUE_IND,
MSG_ID_FDD_DBME_CODE_END = MSG_ID_FDD_DBME_DUMP_EXT_QUEUE_IND,
MODULE_MSG_END( MSG_ID_FDD_DBME_CODE_TAIL )
//MSG_ID_DBME_CODE_END,

//MSG_ID_USIME_CODE_BEGIN,
MODULE_MSG_BEGIN( MSG_ID_FDD_USIME_CODE_BEGIN )
MSG_ID_FDD_RRCE_USIME_SAVE_REQ = MSG_ID_FDD_USIME_CODE_BEGIN,
MSG_ID_FDD_CSCE_USIME_READ_NVRAM_REQ,
MSG_ID_FDD_CSCE_USIME_SAVE_REQ,
MSG_ID_FDD_CSCE_USIME_SET_MODE_REQ,
MSG_ID_FDD_CSCE_USIME_BAND_SETTING_UPDATE_REQ,
MSG_ID_FDD_CSCE_USIME_EUTRAN_CAP_UPDATE_REQ,
MSG_ID_RATCM_UAS_USIM_INFO_RESET_REQ,
MSG_ID_FDD_USIM_REGISTER_CNF,
MSG_ID_FDD_USIME_DUMP_UE_CAPABILITY,
MSG_ID_FDD_NWSEL_USIME_EUTRAN_BAND_UPDATE_REQ,
MSG_ID_FDD_USIME_CODE_END = MSG_ID_FDD_USIM_REGISTER_CNF,
MODULE_MSG_END( MSG_ID_FDD_USIME_CODE_TAIL )
//MSG_ID_USIME_CODE_END,

//MSG_ID_FDD_URR_CODE_BEGIN,
MODULE_MSG_BEGIN( MSG_ID_FDD_URR_CODE_BEGIN )
MSG_ID_URR_NON_USED_MESSAGE_BEGIN = MSG_ID_FDD_URR_CODE_BEGIN,

#ifdef __GEMINI__
MSG_ID_FDD_URR_RRCE_SERVICE_RES_OCCUPY_IND,
MSG_ID_FDD_URR_CSCE_SWITCH_GEMINI_MODE_REQ,

/* ifdef __GEMINI_MONITOR_PAGE_DURING_TRANSFER__ */
MSG_ID_FDD_URR_RRCE_SWITCH_GEMINI_MODE_REQ,
MSG_ID_FDD_URR_CSE_SWITCH_GEMINI_MODE_REQ,
MSG_ID_FDD_URR_MEME_SWITCH_GEMINI_MODE_REQ,
MSG_ID_FDD_URR_SIBE_SWITCH_GEMINI_MODE_REQ,
MSG_ID_FDD_URR_CSCE_VIRTUAL_SUSPEND_SERVICE_COMPLETE_IND,
#if 0 /* move to ul1_sap.h */
/* under construction !*/
#endif
/* endif __GEMINI_MONITOR_PAGE_DURING_TRANSFER__ */
#endif /* __GEMINI__ */

/* DRLC */
MSG_ID_FDD_URR_DRLC_SRB_SDU_STOP_IND,

/* LCSCE */
MSG_ID_FDD_LCSCE_CSCE_RESEL_IND,
MSG_ID_FDD_LCSCE_CSCE_BAR_CELL_IND,
MSG_ID_FDD_LCSCE_CSCE_TRIGGER_4G_CSG_SEARCH_IND,
MSG_ID_FDD_LCSCE_CSCE_TRIGGER_4G_CSG_EVALUATION_IND,
MSG_ID_FDD_LCSCE_CSCE_TRIGGER_3G_CSG_SEARCH_IND,

#ifdef UNIT_TEST
MSG_ID_FDD_LCSCE_CSCE_UT_SIMULATE_CONTEXT_TRANSFER,
#endif /* UNIT_TEST */

/* LURR */
MSG_ID_FDD_URR_LURR_SYNC_UP_REQ,
MSG_ID_FDD_URR_LURR_SYNC_UP_CNF,
MSG_ID_FDD_URR_LURR_SYNC_DOWN_REQ,
MSG_ID_FDD_URR_LURR_DUMP_SYNC_DATA,
MSG_ID_FDD_URR_DUMP_CONTEXT,
	
#ifdef __REMOTE_SIM__
MSG_ID_FDD_URR_RRCE_VIRTUAL_CONNECTED_SUSPEND_REQ,
MSG_ID_FDD_URR_CSCE_VIRTUAL_CONNECTED_SUSPEND_REQ,
MSG_ID_FDD_URR_MEME_VIRTUAL_CONNECTED_SUSPEND_REQ,
MSG_ID_FDD_URR_SIBE_VIRTUAL_CONNECTED_SUSPEND_REQ,

MSG_ID_FDD_URR_RRCE_VIRTUAL_CONNECTED_RESUME_REQ,
MSG_ID_FDD_URR_CSCE_VIRTUAL_CONNECTED_RESUME_REQ,
MSG_ID_FDD_URR_MEME_VIRTUAL_CONNECTED_RESUME_REQ,
MSG_ID_FDD_URR_SIBE_VIRTUAL_CONNECTED_RESUME_REQ,
#endif


MSG_ID_FDD_URR_NON_USED_MESSAGE_END,
MSG_ID_FDD_URR_CODE_END = MSG_ID_FDD_URR_NON_USED_MESSAGE_END,
MODULE_MSG_END( MSG_ID_FDD_URR_CODE_TAIL )
//MSG_ID_FDD_URR_CODE_END,

#endif /* __UMTS_FDD_MODE__ */

/* mtk80197, merge TDD128 back to MAUI */
#if defined(__UMTS_TDD128_MODE__)
MODULE_MSG_BEGIN( MSG_ID_TDD_ADR_CODE_BEGIN )

//MSG_ID_TDD_ADR_CODE_BEGIN,
MSG_ID_TDD_RLC_TM_DATA_IND = MSG_ID_TDD_ADR_CODE_BEGIN,
MSG_ID_TDD_RLC_UM_DATA_IND,
MSG_ID_TDD_RLC_AM_DATA_IND,

#ifdef UNIT_TEST
MSG_ID_TDD_ADR_UNPACK_UT_EVENT_PHY_DATA_IND,
MSG_ID_TDD_ADR_UNPACK_UT_EVENT_RLC_DATA_IND,
MSG_ID_TDD_ADR_UNPACK_UT_EVENT_VERDICT_DATA_IND,
MSG_ID_TDD_ADR_PACK_UT_MOVE_TO_IDLE_REQ,
MSG_ID_TDD_ADR_PACK_UT_SEND_CCCH_REQ,
MSG_ID_TDD_ADR_PACK_UT_SEND_DCCH_REQ,
#endif

MSG_ID_TDD_ADR_ADR_ACKNOWLEDGEMENT_IND,
MSG_ID_TDD_RLC_AM_DATA_CNF,
MSG_ID_TDD_ADR_CODE_END = MSG_ID_TDD_RLC_AM_DATA_CNF,
MODULE_MSG_END( MSG_ID_TDD_ADR_CODE_TAIL )
//MSG_ID_TDD_ADR_CODE_END,

//MSG_ID_TDD_CSCE_CODE_BEGIN,
//SLCE
MODULE_MSG_BEGIN( MSG_ID_TDD_CSCE_CODE_BEGIN )
MSG_ID_TDD_URR_SLCE_SET_ACTIVE_RAT_CNF = MSG_ID_TDD_CSCE_CODE_BEGIN,  /*Alfie: this msg_id is also used by RRCE*/
MSG_ID_TDD_CSCE_SLCE_INITIALISE_CNF,
MSG_ID_TDD_CSCE_SLCE_RF_ON_CNF,
MSG_ID_TDD_CSCE_SLCE_RF_OFF_CNF,
MSG_ID_TDD_CSCE_SLCE_RSSI_SNIFFER_STOP_CNF,

//RRCE
MSG_ID_TDD_CSCE_RRCE_MOVE_TO_IDLE_IND,
MSG_ID_TDD_CSCE_RRCE_MOVE_TO_CELL_DCH_IND,
MSG_ID_TDD_CSCE_RRCE_MOVE_TO_CONNECTED_IND,
MSG_ID_TDD_CSCE_RRCE_MOVE_TO_INACTIVE_IND,
MSG_ID_TDD_CSCE_RRCE_BCCH_MODIFICATION_INFO_IND,
MSG_ID_TDD_CSCE_RRCE_RRC_CONNECTION_ESTABLISHMENT_IND,
MSG_ID_TDD_CSCE_RRCE_RELEASE_CHANNELS_CNF,
MSG_ID_TDD_CSCE_RRCE_OUT_OF_SERVICE_AREA_CNF,
MSG_ID_TDD_RRCE_CSCE_SIB_COLLECTION_RSP,
MSG_ID_TDD_CSCE_RRCE_STEADY_INACTIVE_IND,

#if defined(__23G_PRI_RESEL_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_TDD_CSCE_RRCE_DEDI_PRIO_INFO_IND,
#endif

#ifdef __GEMINI_PREEMPT_PEER_SERVICE__
MSG_ID_TDD_CSCE_RRCE_ABORT_SERVICE_REQ,
MSG_ID_TDD_CSCE_RRCE_ABORT_SERVICE_COMPLETE_IND,
#endif

#ifdef __GEMINI__
MSG_ID_TDD_CSCE_RRCE_REVERT_RAT_IN_SUSPEND_IND,
#endif
MSG_ID_TDD_CSCE_RRCE_CHANNEL_CONFIG_FAILURE_IND,
#ifdef __SMART_PAGING_3G_FDD__
MSG_ID_TDD_CSCE_RRCE_SMART_PAGING_STATUS_IND,
#endif

//CSE
MSG_ID_TDD_CSCE_CSE_CELL_SELECTION_STOP_CNF,
MSG_ID_TDD_CSCE_CSE_CELL_SELECTION_CNF,
MSG_ID_TDD_CSCE_CSE_PLMN_LIST_CNF,
MSG_ID_TDD_CSCE_CSE_FREQ_SCAN_SUSPEND_IND,

#if 0
#ifdef __WCDMA_PREFERRED__
/* under construction !*/
/* under construction !*/
#endif
#endif
#if (defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__))
MSG_ID_TDD_CSCE_CSE_CSG_LIST_CNF,
MSG_ID_TDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_SUSPEND_CNF,
MSG_ID_TDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_CNF,
MSG_ID_TDD_MEME_CSE_CSG_AUTONOMOUS_SEARCH_INTRA_FREQ_CELL_IND,
MSG_ID_TDD_CSCE_CSE_EVALUATE_CSG_CELL_CNF,
MSG_ID_TDD_CSCE_CSE_EVALUATE_CSG_CELL_SUSPEND_CNF,
#endif

#ifdef __LTE_RAT__
MSG_ID_TDD_CSCE_CSE_CGI_COLLECTION_CNF,
MSG_ID_TDD_CSCE_CSE_CGI_COLLECTION_STOP_CNF,
#endif /* __LTE_RAT__ */

//SIBE
MSG_ID_TDD_SIBE_SIB_COLLECTION_CNF,
MSG_ID_TDD_SIBE_SIB_MONITORING_CNF,
MSG_ID_TDD_SIBE_SIB_MONITORING_ERROR_IND,
MSG_ID_TDD_CSCE_SIBE_MIB_CHANGE_IND,
//MEME
MSG_ID_TDD_CSCE_MEME_CELL_MEASUREMENT_RESULT_IND,
MSG_ID_TDD_CSCE_MEME_LTE_MEASUREMENT_IND,
MSG_ID_TDD_CSCE_MEME_CELL_REF_TIME_ANCHOR_IND,
MSG_ID_TDD_MEME_CSCE_MODIFY_CELL_LIST_IND,
MSG_ID_TDD_CSCE_MEME_REF_CELL_CHANGE_IND,
//USIME
MSG_ID_TDD_CSCE_USIME_USIM_REMOVED_IND,
MSG_ID_TDD_CSCE_USIME_READ_NVRAM_CNF,
MSG_ID_TDD_USIME_SIM_FILE_CHANGE_IND,


//RATCM
MSG_ID_TDD_RATCM_CSCE_INIT_REQ,
MSG_ID_RATCM_CSCE_PLMN_SEARCH_ABORT_REQ,
MSG_ID_RATCM_CSCE_ARAL_UPDATE_REQ,
#if !defined(__UMTS_FDD_MODE__)
MSG_ID_RATCM_CSCE_PLMN_SEARCH_REQ,
MSG_ID_RATCM_CSCE_PLMN_LIST_REQ,
MSG_ID_RATCM_CSCE_PLMN_LIST_STOP_REQ,
MSG_ID_RATCM_CSCE_ADD_FORBIDDEN_LA_REQ,
MSG_ID_RATCM_CSCE_DEL_FORBIDDEN_LA_REQ,
MSG_ID_RATCM_CSCE_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_RATCM_CSCE_HPLMN_INFO_UPDATE_REQ,
MSG_ID_RATCM_CSCE_RRC_DEACTIVATE_REQ,
MSG_ID_RATCM_CSCE_SET_RAT_MODE_REQ,
MSG_ID_RATCM_CSCE_RFON_REQ,
MSG_ID_RATCM_CSCE_RFOFF_REQ,

//CM
MSG_ID_CMCSCE_EMERGENCY_CALL_STATUS_IND,
#ifdef __GEMINI__
MSG_ID_RATCM_CSCE_SIM_STATUS_UPDATE_REQ,
#endif

#if defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__)
MSG_ID_RATCM_CSCE_CSG_LIST_REQ,
MSG_ID_RATCM_CSCE_CSG_LIST_STOP_REQ,
MSG_ID_RATCM_CSCE_UPDATE_WHITE_LIST_REQ,
#endif
MSG_ID_RATCM_CSCE_PLMN_LIST_STATUS_UPDATE_REQ,


#ifdef __LTE_RAT__
MSG_ID_RATCM_UAS_RAT_CHANGE_REQ,  //also used by RRCE
MSG_ID_RATCM_CSCE_EUTRAN_CAP_UPDATE_REQ,
#endif

MSG_ID_RATCM_CSCE_REGN_STATUS_UPDATE_REQ,

MSG_ID_TDD_CSCE_CODE_END = MSG_ID_RATCM_CSCE_REGN_STATUS_UPDATE_REQ,
#else
MSG_ID_TDD_CSCE_CODE_END = MSG_ID_TDD_RATCM_CSCE_INIT_REQ,
#endif
MODULE_MSG_END( MSG_ID_TDD_CSCE_CODE_TAIL )
//MSG_ID_TDD_CSCE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_TDD_CSE_CODE_BEGIN )
//MSG_ID_TDD_CSE_CODE_BEGIN,
//SLCE
MSG_ID_TDD_CSE_SLCE_FREQ_SCAN_SUSPEND_IND = MSG_ID_TDD_CSE_CODE_BEGIN,
// MEME
MSG_ID_TDD_CSE_MEME_CELL_MEASUREMENT_RESULT_IND,
// CSCE
MSG_ID_TDD_CSCE_CSE_CELL_SELECTION_START_REQ,
MSG_ID_TDD_CSCE_CSE_CELL_SELECTION_STOP_REQ,
MSG_ID_TDD_CSCE_CSE_PLMN_LIST_START_REQ,
MSG_ID_TDD_CSCE_CSE_PLMN_LIST_SUSPEND_REQ,
MSG_ID_TDD_CSCE_CSE_RF_OFF_REQ,                             // For auto band
MSG_ID_TDD_CSCE_CSE_PLMN_LOSS_WITH_LIST_IND,                // For PLMN List optimization
MSG_ID_TDD_CSE_SLCE_FREQ_SCAN_CNF,

#if 0
#ifdef __WCDMA_PREFERRED__
/* under construction !*/
/* under construction !*/
#endif
#endif
#if (defined(__3G_CSG_SUPPORT__) || defined(__LTE_RAT__))
MSG_ID_TDD_CSCE_CSE_CSG_LIST_START_REQ,
MSG_ID_TDD_CSCE_CSE_CSG_LIST_SUSPEND_REQ,
MSG_ID_TDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_START_REQ,
MSG_ID_TDD_CSCE_CSE_CSG_AUTONOMOUS_SEARCH_SUSPEND_REQ,
MSG_ID_TDD_CSCE_CSE_EVALUATE_CSG_CELL_REQ,
MSG_ID_TDD_CSCE_CSE_EVALUATE_CSG_CELL_SUSPEND_REQ,
#endif

#ifdef __LTE_RAT__
MSG_ID_TDD_CSCE_CSE_CGI_COLLECTION_REQ,
MSG_ID_TDD_CSCE_CSE_CGI_COLLECTION_STOP_REQ,
#endif

MSG_ID_TDD_CSE_CACHE_INFO_IND,                              // For showing cache content to Catcher...>#I
MSG_ID_TDD_CSE_CODE_END = MSG_ID_TDD_CSE_CACHE_INFO_IND,
MODULE_MSG_END( MSG_ID_TDD_CSE_CODE_TAIL )
//MSG_ID_TDD_CSE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_TDD_MEME_CODE_BEGIN )
//MSG_ID_TDD_MEME_CODE_BEGIN,
//SLCE
//UMAC
MSG_ID_TDD_MEME_UMAC_TRAFFIC_VOLUME_MEASUREMENT_IND = MSG_ID_TDD_MEME_CODE_BEGIN,
MSG_ID_TDD_MEME_UMAC_QUALITY_MEASUREMENT_IND,
MSG_ID_TDD_MEME_UMAC_ADDITIONAL_TVM_IND,
MSG_ID_TDD_MEME_UMAC_MEASUREMENT_ERROR_IND,
#ifdef __UMTS_R6__
MSG_ID_TDD_MEME_UMAC_TVM_EXCEED_THRESHOLD_IND,
#endif
MSG_ID_TDD_MEME_UMAC_CS_CIPHER_STATUS_IND,
//RRCE
MSG_ID_TDD_RRCE_MEME_MOVE_TO_STATE_REQ,
MSG_ID_TDD_MEME_RRCE_COMPRESSED_MODE_RECONFIGURE_FAILURE_IND,
MSG_ID_TDD_MEME_RRCE_COMPRESSED_MODE_RECONFIGURE_SUCCESS_IND,


//SLCE
MSG_ID_TDD_MEME_SLCE_SUSPEND_REPORT_IND,
MSG_ID_TDD_MEME_SLCE_RESUME_REPORT_IND,

//CSCE
MSG_ID_TDD_CSCE_MEME_INITIALISE_REQ,
//MSG_ID_MEME_CSCE_CELL_RESELECTION_IND,	
MSG_ID_TDD_MEME_CSCE_CELL_SELECTED_IND,
MSG_ID_TDD_CSCE_MEME_MEAS_MANIPULATION_REQ,
MSG_ID_TDD_CSCE_MEME_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_TDD_CSCE_MEME_RF_ON_REQ,
MSG_ID_TDD_CSCE_MEME_RF_OFF_REQ,
MSG_ID_TDD_CSCE_MEME_SET_MODE_REQ,
MSG_ID_TDD_CSCE_MEME_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_TDD_CSCE_MEME_CLEAN_DB_CELL_REQ,
//SIBE
MSG_ID_TDD_MEME_SIBE_SIB3_CHANGE_IND,
MSG_ID_TDD_MEME_SIBE_SIB4_CHANGE_IND,
MSG_ID_TDD_MEME_SIBE_SIB11_CHANGE_IND, 
MSG_ID_TDD_MEME_SIBE_SIB12_CHANGE_IND, 
MSG_ID_TDD_MEME_SIBE_SIB18_CHANGE_IND, 
//MEME self
MSG_ID_TDD_MEME_DUMP_CONTEXT,
MSG_ID_TDD_MEME_UT_SET_CONTEXT,
MSG_ID_TDD_MEME_UT_SET_SHM,
MSG_ID_TDD_MEME_CELL_POWER_LEVEL_IND,
MSG_ID_TDD_MEME_MEME_SAVED_MEAS_CTRL_IND,

MSG_ID_TDD_MEME_CODE_END = MSG_ID_TDD_MEME_MEME_SAVED_MEAS_CTRL_IND,
//MSG_ID_TDD_MEME_CODE_END,
MODULE_MSG_END( MSG_ID_TDD_MEME_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_TDD_RRCE_CODE_BEGIN )
//MSG_ID_TDD_RRCE_CODE_BEGIN,
//UDC
MSG_ID_RATCM_RRCE_FORCE_REL_REQ = MSG_ID_TDD_RRCE_CODE_BEGIN,
//NEW
#if defined (__NO_PSDATA_SEND_SCRI__) || defined (__FAST_DORMANCY__)
MSG_ID_RATCM_RRCE_SERVICE_ACCEPT_NOTIFY_REQ,
#endif /* __NO_PSDATA_SEND_SCRI__ || __FAST_DORMANCY__ */

/* BMC */
MSG_ID_TDD_RRCE_BMC_RX_IND,
MSG_ID_TDD_RRCE_BMC_ETWS_IND,
/* URLC */
MSG_ID_TDD_RRCE_URLC_STATUS_IND,

//SLCE
MSG_ID_TDD_RRCE_SLCE_RECONFIG_COMPLETE_IND,
MSG_ID_TDD_RRCE_SLCE_RECONFIG_ERROR_IND,
MSG_ID_TDD_RRCE_SLCE_PDCP_RELOC_IND,
MSG_ID_TDD_RRCE_SLCE_GET_COUNT_C_CNF,
MSG_ID_TDD_RRCE_SLCE_ABORT_CNF,
MSG_ID_TDD_RRCE_SLCE_ACTIVATION_TIME_IND,

//SIBE
MSG_ID_TDD_RRCE_SIBE_CELL_RST_CNF,
MSG_ID_TDD_RRCE_SIBE_CELL_RST_STOP_CNF,
//CSCE
MSG_ID_TDD_CSCE_RRCE_SUITABLE_CELL_SELECTED_REQ,
MSG_ID_TDD_CSCE_RRCE_ACCEPTABLE_CELL_SELECTED_REQ,
MSG_ID_TDD_CSCE_RRCE_OUT_OF_SERVICE_AREA_REQ,
MSG_ID_TDD_CSCE_RRCE_DEACTIVATE_REQ,
MSG_ID_TDD_CSCE_RRCE_SET_MODE_REQ,
MSG_ID_TDD_RRCE_CSCE_SIB_COLLECTION_IND,
MSG_ID_TDD_CSCE_RRCE_PCH_TO_FACH_READY_RSP,
MSG_ID_TDD_CSCE_RRCE_RELEASE_CHANNELS_REQ,
//MEME
//MSG_ID_MEME_RRCE_COMPRESSED_MODE_RECONFIGURE_REQ,  //FDD only
//UMAC
MSG_ID_TDD_RRCE_UMAC_STATUS_DATA_PENDING_IND,
MSG_ID_TDD_RRCE_UMAC_STATUS_RACH_IND,
#ifdef __HSUPA_SUPPORT__
MSG_ID_TDD_RRCE_UMAC_RL_FAILURE_IND,
#endif
#ifdef __TDD_ENHANCED_COMMON_STATE_SUPPORT__
MSG_ID_TDD_RRCE_UMAC_D_HRNTI_DETECTED_IND,
#endif
#ifdef __MTK_INTERNAL__
// RRCE itself
MSG_ID_TDD_RRCE_RRCE_DEBUG_INFO_IND,
#endif
/* ACK */
MSG_ID_TDD_RRCL_RRC_ACKNOWLEDGEMENT_IND,
MSG_ID_TDD_RRCE_TIMERID_IND, // Event Scheduler, UT: Oneshot Timer id verification */
MSG_ID_TDD_RRCE_CODE_END = MSG_ID_TDD_RRCE_TIMERID_IND,
MODULE_MSG_END( MSG_ID_TDD_RRCE_CODE_TAIL )
//MSG_ID_TDD_RRCE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_TDD_SIBE_CODE_BEGIN )
//MSG_ID_TDD_SIBE_CODE_BEGIN,
//SLCE
MSG_ID_TDD_SIBE_SLCE_CONFIGURE_BCH_FAILED_IND = MSG_ID_TDD_SIBE_CODE_BEGIN,
MSG_ID_TDD_SIBE_SLCE_RECONFIGURE_BCH_CNF,
// SIBE self
MSG_ID_TDD_SIBE_SIB_COLLECTION_REQ,
MSG_ID_TDD_SIBE_SIB_COLLECTION_CANCEL_REQ,
MSG_ID_TDD_SIBE_START_SIB_MONITORING_REQ,
MSG_ID_TDD_SIBE_STOP_SIB_MONITORING_REQ,
MSG_ID_TDD_RRCE_SIBE_CELL_RST_REQ,
MSG_ID_TDD_RRCE_SIBE_CELL_RST_STOP_REQ,
#ifdef __UMTS_R9__
MSG_ID_TDD_RRCE_SIBE_SIB7_EXPIRY_TIMER_IND,
#endif
MSG_ID_TDD_CSCE_SIBE_MOVE_TO_IDLE_REQ,
MSG_ID_TDD_SIBE_DUMP_BCH_SIB_IND,
MSG_ID_TDD_SIBE_SIB_CHANGE_IND,// remember to Sync FDD,and Put it to SIBE's location(before MSG_ID_SIBE_CODE_END)
MSG_ID_TDD_SIBE_CODE_END = MSG_ID_TDD_SIBE_DUMP_BCH_SIB_IND,
//MSG_ID_TDD_SIBE_CODE_END,
MODULE_MSG_END( MSG_ID_TDD_SIBE_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_TDD_SLCE_CODE_BEGIN )
//MSG_ID_TDD_SLCE_CODE_BEGIN,
//RATCM

/* RABM */
MSG_ID_TDD_CRABM_RAB_ESTABLISH_RSP = MSG_ID_TDD_SLCE_CODE_BEGIN,
MSG_ID_TDD_CRABM_RAB_RELEASE_RSP,
/* PDCP */
MSG_ID_TDD_CPDCP_CONFIG_CNF,
MSG_ID_TDD_CPDCP_RELOC_CNF,
MSG_ID_TDD_CPDCP_RELEASE_CNF,
/* URLC */
MSG_ID_TDD_CRLC_CONFIG_RAB_CNF,
MSG_ID_TDD_CRLC_CONFIG_TM_ESTABLISH_CNF,
MSG_ID_TDD_CRLC_CONFIG_UM_ESTABLISH_CNF,
MSG_ID_TDD_CRLC_CONFIG_AM_ESTABLISH_CNF,
MSG_ID_TDD_CRLC_CONFIG_RELEASE_CNF,
MSG_ID_TDD_CRLC_SUSPEND_CNF,
MSG_ID_TDD_CRLC_RESUME_CNF,
MSG_ID_TDD_CRLC_CONFIG_TX_CIPHERING_CNF,
MSG_ID_TDD_CRLC_CONFIG_RX_CIPHERING_CNF,
MSG_ID_TDD_CRLC_COUNT_C_CNF,

//CSCE
MSG_ID_TDD_CSCE_SLCE_INITIALISE_REQ,
MSG_ID_TDD_CSCE_SLCE_RF_OFF_REQ,
MSG_ID_TDD_CSCE_SLCE_RF_ON_REQ,
MSG_ID_TDD_CSCE_SLCE_RSSI_SNIFFER_START_REQ,
MSG_ID_TDD_CSCE_SLCE_RSSI_SNIFFER_STOP_REQ,
MSG_ID_TDD_CSCE_SLCE_RSSI_SNIFFER_STOP_IND,

#ifdef __GEMINI__
MSG_ID_TDD_CSCE_SLCE_RESUME_REQ,
#endif

//URR
MSG_ID_TDD_URR_SLCE_SET_ACTIVE_RAT_REQ,
//RRCE
MSG_ID_TDD_RRCE_SLCE_ABORT_REQ,
MSG_ID_TDD_RRCE_SLCE_GET_COUNT_C_REQ,
MSG_ID_TDD_RRCE_SLCE_RECONFIG_REQ,
//SIBE
MSG_ID_TDD_SIBE_SLCE_RECONFIGURE_BCH_REQ,
MSG_ID_TDD_SIBE_SLCE_SIB7_CHANGE_IND,
//FDD_CSE
MSG_ID_TDD_CSE_SLCE_FREQ_SCAN_CONTINUE_REQ,
MSG_ID_TDD_CSE_SLCE_FREQ_SCAN_REQ,
MSG_ID_TDD_CSE_SLCE_FREQ_SCAN_SUSPEND_REQ,
MSG_ID_TDD_CSE_SLCE_SPECIFIC_CELL_SEARCH_REQ,
MSG_ID_TDD_CSE_SLCE_SPECIFIC_CELL_SEARCH_STOP_REQ,
//MEME
MSG_ID_TDD_MEME_SLCE_ADDITIONAL_TVM_REQ,
MSG_ID_TDD_MEME_SLCE_MEASUREMENT_CONFIG_CELL_REQ,
MSG_ID_TDD_MEME_SLCE_MEASUREMENT_CONFIG_FMO_REQ,
MSG_ID_TDD_MEME_SLCE_MEASUREMENT_CONFIG_TGPS_REQ,
MSG_ID_TDD_MEME_SLCE_MEASUREMENT_CONFIG_GSMGAP_REQ,
MSG_ID_TDD_MEME_SLCE_RLC_CONTINUE_REQ,
MSG_ID_TDD_MEME_SLCE_RLC_STOP_REQ,
MSG_ID_TDD_MEME_SLCE_QUALITY_MEASUREMENT_REQ,
MSG_ID_TDD_MEME_SLCE_TVM_MEASUREMENT_REQ,
MSG_ID_TDD_MEME_SLCE_MEASUREMENT_CONFIG_DMO_REQ,
//SEQ
MSG_ID_TDD_SEQ_SEQUENCE_REQ,
MSG_ID_TDD_SEQ_SEQUENCE_CONFIRMED_IND,
MSG_ID_TDD_SEQ_SEQUENCE_INDICATED_IND,
MSG_ID_TDD_SEQ_SEQUENCE_ERROR_IND,

//UMAC
MSG_ID_TDD_CMAC_CONFIG_UE_CNF,
MSG_ID_TDD_CMAC_CONFIG_UE_IND,
MSG_ID_TDD_CMAC_CONFIG_TX_CCTRCH_CNF,
MSG_ID_TDD_CMAC_CONFIG_TX_CCTRCH_IND,
MSG_ID_TDD_CMAC_REMOVE_TX_CCTRCH_CNF,
MSG_ID_TDD_CMAC_REMOVE_TX_CCTRCH_IND,
MSG_ID_TDD_CMAC_CONFIG_RX_CCTRCH_CNF,
MSG_ID_TDD_CMAC_CONFIG_RX_CCTRCH_IND,
MSG_ID_TDD_CMAC_REMOVE_RX_CCTRCH_CNF,
MSG_ID_TDD_CMAC_REMOVE_RX_CCTRCH_IND,
MSG_ID_TDD_CMAC_CONFIG_HSDSCH_CCTRCH_CNF,
MSG_ID_TDD_CMAC_CONFIG_HSDSCH_CCTRCH_IND,
MSG_ID_TDD_CMAC_REMOVE_HSDSCH_CCTRCH_CNF,
MSG_ID_TDD_CMAC_REMOVE_HSDSCH_CCTRCH_IND,
#ifdef __HSUPA_SUPPORT__
MSG_ID_TDD_CMAC_CONFIG_EDCH_CCTRCH_CNF,
MSG_ID_TDD_CMAC_CONFIG_EDCH_CCTRCH_IND,
MSG_ID_TDD_CMAC_REMOVE_EDCH_CCTRCH_CNF,
MSG_ID_TDD_CMAC_REMOVE_EDCH_CCTRCH_IND,
#endif
MSG_ID_TDD_CMAC_CONFIG_RACH_CNF,
MSG_ID_TDD_CMAC_CONFIG_RACH_IND,
MSG_ID_TDD_CMAC_CONFIG_CPCH_CNF,
MSG_ID_TDD_CMAC_CONFIG_CIPHERING_CNF,
MSG_ID_TDD_CMAC_COUNT_C_CNF,
MSG_ID_TDD_CMAC_DELETE_CIPHERING_CNF,
MSG_ID_TDD_CMAC_CONFIG_TX_RLC_MODIFY_CNF,
MSG_ID_TDD_CMAC_CONFIG_TX_RLC_MODIFY_IND,
MSG_ID_TDD_CMAC_CONFIG_RX_RLC_MODIFY_CNF,
MSG_ID_TDD_CMAC_CONFIG_RX_RLC_MODIFY_IND,
MSG_ID_TDD_CMAC_CONFIG_ABORT_CNF,
MSG_ID_TDD_CMAC_CONFIG_TFC_SUBSET_CNF,
MSG_ID_TDD_CMAC_CONFIG_TFC_SUBSET_IND,

MSG_ID_TDD_SLCE_CODE_END = MSG_ID_TDD_CMAC_CONFIG_TFC_SUBSET_IND,
MODULE_MSG_END( MSG_ID_TDD_SLCE_CODE_TAIL )
//MSG_ID_TDD_SLCE_CODE_END,

MODULE_MSG_BEGIN( MSG_ID_TDD_DBME_CODE_BEGIN )
//MSG_ID_TDD_DBME_CODE_BEGIN,
MSG_ID_TDD_DBME_DUMP_IND = MSG_ID_TDD_DBME_CODE_BEGIN,
MSG_ID_TDD_DBME_DUMP_EXT_QUEUE_IND,
MSG_ID_TDD_DBME_CODE_END = MSG_ID_TDD_DBME_DUMP_EXT_QUEUE_IND,
MODULE_MSG_END( MSG_ID_TDD_DBME_CODE_TAIL )
//MSG_ID_TDD_DBME_CODE_END,

//MSG_ID_TDD_USIME_CODE_BEGIN,
MODULE_MSG_BEGIN( MSG_ID_TDD_USIME_CODE_BEGIN )
MSG_ID_TDD_RRCE_USIME_SAVE_REQ = MSG_ID_TDD_USIME_CODE_BEGIN,
MSG_ID_TDD_CSCE_USIME_READ_NVRAM_REQ,
MSG_ID_TDD_CSCE_USIME_SET_MODE_REQ,
MSG_ID_TDD_CSCE_USIME_BAND_SETTING_UPDATE_REQ,
MSG_ID_TDD_CSCE_USIME_EUTRAN_CAP_UPDATE_REQ,
MSG_ID_TDD_USIME_DUMP_UE_CAPABILITY,
MSG_ID_TDD_USIM_REGISTER_CNF,
MSG_ID_TDD_USIME_CODE_END = MSG_ID_TDD_USIM_REGISTER_CNF,
MODULE_MSG_END( MSG_ID_TDD_USIME_CODE_TAIL )
//MSG_ID_TDD_USIME_CODE_END,

//MSG_ID_TDD_URR_CODE_BEGIN,
MODULE_MSG_BEGIN( MSG_ID_TDD_URR_CODE_BEGIN )
MSG_ID_TDD_URR_NON_USED_MESSAGE_BEGIN = MSG_ID_TDD_URR_CODE_BEGIN,

#ifdef __GEMINI__
MSG_ID_TDD_URR_RRCE_SERVICE_RES_OCCUPY_IND,
MSG_ID_TDD_URR_CSCE_SWITCH_GEMINI_MODE_REQ,

/* ifdef __GEMINI_MONITOR_PAGE_DURING_TRANSFER__ */
MSG_ID_TDD_URR_RRCE_SWITCH_GEMINI_MODE_REQ,
MSG_ID_TDD_URR_CSE_SWITCH_GEMINI_MODE_REQ,
MSG_ID_TDD_URR_MEME_SWITCH_GEMINI_MODE_REQ,
MSG_ID_TDD_URR_SIBE_SWITCH_GEMINI_MODE_REQ,
MSG_ID_TDD_URR_CSCE_VIRTUAL_SUSPEND_SERVICE_COMPLETE_IND,
#if 0 /* move to ul1_sap.h */
/* under construction !*/
#endif
/* endif __GEMINI_MONITOR_PAGE_DURING_TRANSFER__ */
#endif /* __GEMINI__ */

/* DRLC */
MSG_ID_TDD_URR_DRLC_SRB_SDU_STOP_IND,

/*LURR*/
MSG_ID_TDD_URR_LURR_SYNC_UP_REQ,
MSG_ID_TDD_URR_LURR_SYNC_UP_CNF,
MSG_ID_TDD_URR_LURR_SYNC_DOWN_REQ,
MSG_ID_TDD_URR_LURR_DUMP_SYNC_DATA,

/* LCSCE */
MSG_ID_TDD_LCSCE_CSCE_RESEL_IND,
MSG_ID_TDD_LCSCE_CSCE_BAR_CELL_IND,
MSG_ID_TDD_LCSCE_CSCE_TRIGGER_4G_CSG_SEARCH_IND,
MSG_ID_TDD_LCSCE_CSCE_TRIGGER_4G_CSG_EVALUATION_IND,
MSG_ID_TDD_LCSCE_CSCE_TRIGGER_3G_CSG_SEARCH_IND,
#ifdef __CMCC_23G_PINGPONG_RESTRAIN__
MSG_ID_TDD_LCSCE_CSCE_GAS_UAS_VIRTUAL_CELL_RESEL_IND,
#endif /* __CMCC_23G_PINGPONG_RESTRAIN__ */
#ifdef UNIT_TEST
MSG_ID_TDD_LCSCE_CSCE_UT_SIMULATE_CONTEXT_TRANSFER,
#endif /* UNIT_TEST */
MSG_ID_TDD_URR_DUMP_CONTEXT,

/*LRRCE*/
MSG_ID_TDD_RRCE_LRRCE_PAGING_TYPE1_IND,


MSG_ID_TDD_URR_NON_USED_MESSAGE_END,
MSG_ID_TDD_URR_CODE_END = MSG_ID_TDD_URR_NON_USED_MESSAGE_END,
MODULE_MSG_END( MSG_ID_TDD_URR_CODE_TAIL )
//MSG_ID_TDD_URR_CODE_END,

#endif /* __UMTS_TDD128_MODE__ */


#ifdef __SOURCE_INSIGHT_PARSE__
};
#endif

#endif  //_URR_MSG_H
